default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: libros_development
  username: postgres
  password: 1212
  host: localhost

test:
  <<: *default
  database: libros_test
  username: postgres
  password: 1212
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://dummy:dummy@localhost/dummy' %>