default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "libros_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "libros_test") %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] if ENV["DATABASE_URL"] %>
  host: <%= ENV["PGHOST"] if ENV["PGHOST"] %>
  port: <%= ENV["PGPORT"] if ENV["PGPORT"] %>
  database: <%= ENV["PGDATABASE"] if ENV["PGDATABASE"] %>
  username: <%= ENV["PGUSER"] if ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] if ENV["PGPASSWORD"] %>