name: Close Issues on Master Merge

on:
  push:
    branches:
      - main  # Solo cuando haya un merge/push a master

jobs:
  close-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Trae todo el historial de commits

      - name: Get commit messages
        id: get_commits
        run: |
          # Extrae todos los mensajes de commit en este push
          COMMITS=$(git log --pretty=%B ${{ github.event.before }}..${{ github.sha }})
          echo "$COMMITS" > commits.txt

      - name: Find issue references
        id: find_issues
        run: |
          issues=$(grep -oE '#[0-9]+' commits.txt | tr -d '#' | sort -u)
          echo "issues=$issues" > issues.txt

      - name: Close referenced issues
        if: ${{ steps.find_issues.outputs.issues != '' }}
        run: |
          issues=$(cat issues.txt)
          for issue in $issues; do
            echo "Closing issue #$issue"
            gh issue close $issue --comment "Closed automatically: fix was merged into main."
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
