name: Test Secrets Configuration

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check FTP Secrets
        run: |
          echo "Checking if secrets are available..."
          
          if [ -z "${{ secrets.FTP_SERVER }}" ]; then
            echo "❌ FTP_SERVER secret is missing or empty"
            exit 1
          else
            echo "✅ FTP_SERVER is configured"
            echo "Server: ${{ secrets.FTP_SERVER }}"
          fi
          
          if [ -z "${{ secrets.FTP_USERNAME }}" ]; then
            echo "❌ FTP_USERNAME secret is missing or empty"
            exit 1
          else
            echo "✅ FTP_USERNAME is configured"
            echo "Username: ${{ secrets.FTP_USERNAME }}"
          fi
          
          if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
            echo "❌ FTP_PASSWORD secret is missing or empty"
            exit 1
          else
            echo "✅ FTP_PASSWORD is configured (length: ${#{{ secrets.FTP_PASSWORD }}})"
          fi
          
          echo "All secrets are properly configured! 🎉"